Print Hello World from Properties File
NachiketaVadera/100-ways-to-print-HelloWorld-in-java pull request #57
Opened 2020-10-05 05:18 UTC by vaishakhvh

Print Hello World from Properties File. (Related to issue #48 )

2020-10-05 05:57 UTC, NachiketaVadera requested changes
@vaishakhvh Hey! Nice one. Just one change before I can merge this in. Could you please move everything into a single folder with title same or similar as `HelloWorld_FromFile`? Thank you.

2020-10-06 04:56 UTC, vaishakhvh commented
@NachiketaVadera Have moved the files to HelloWorld_FromPropertiesFile folder. Please review and merge the same.

2020-10-06 05:39 UTC, NachiketaVadera approved these changes

2020-10-06 05:40 UTC, NachiketaVadera commented
@vaishakhvh Great! Thank you for your contribution!

2020-10-06 05:40 UTC, merged