HelloWorld in Matrix
NachiketaVadera/100-ways-to-print-HelloWorld-in-java pull request #58
Opened 2020-10-05 07:10 UTC by rufatiani

2020-10-05 08:55 UTC, NachiketaVadera requested changes
@rufatiani Amazing! Just a minor change though. Could you please change the class name to match the file name? Thank you!

2020-10-06 02:57 UTC, rufatiani commented
> 
> 
> @rufatiani Amazing! Just a minor change though. Could you please change the class name to match the file name? Thank you!

Sure, already updated the class name.

2020-10-06 06:05 UTC, NachiketaVadera approved these changes

2020-10-06 06:06 UTC, NachiketaVadera commented
@rufatiani Brilliant. Thank you for your contribution!

2020-10-06 06:06 UTC, merged